name: R-CMD-check
on: [push, pull_request]
jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release'}
          - {os: ubuntu-20.04, r: 'devel'}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
      - name: Create Conda Environment and Install Python Packages
        run: |
          conda create --name GeneSelectR_env
          conda activate GeneSelectR_env
          conda install -c conda-forge scikit-learn=0.22.1 pandas=1.2.3 numpy=1.19 lightgbm boruta_py
      - uses: r-lib/actions/check@v1
